
export default new Map([
["content/blog/2026/designing-personal-publication/de.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=content%2Fblog%2F2026%2Fdesigning-personal-publication%2Fde.mdx&astroContentModuleFlag=true")],
["content/blog/2026/designing-personal-publication/en.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=content%2Fblog%2F2026%2Fdesigning-personal-publication%2Fen.mdx&astroContentModuleFlag=true")],
["content/blog/2026/designing-personal-publication/fr.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=content%2Fblog%2F2026%2Fdesigning-personal-publication%2Ffr.mdx&astroContentModuleFlag=true")],
["content/blog/2026/designing-personal-publication/ja.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=content%2Fblog%2F2026%2Fdesigning-personal-publication%2Fja.mdx&astroContentModuleFlag=true")],
["content/blog/2026/designing-personal-publication/zh-CN.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=content%2Fblog%2F2026%2Fdesigning-personal-publication%2Fzh-CN.mdx&astroContentModuleFlag=true")],
["content/blog/2026/future-of-static-web/en.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=content%2Fblog%2F2026%2Ffuture-of-static-web%2Fen.mdx&astroContentModuleFlag=true")],
["content/blog/2026/future-of-static-web/ja.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=content%2Fblog%2F2026%2Ffuture-of-static-web%2Fja.mdx&astroContentModuleFlag=true")],
["content/blog/2026/future-of-static-web/zh-CN.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=content%2Fblog%2F2026%2Ffuture-of-static-web%2Fzh-CN.mdx&astroContentModuleFlag=true")],
["content/blog/2026/unreleased-draft/en.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=content%2Fblog%2F2026%2Funreleased-draft%2Fen.mdx&astroContentModuleFlag=true")]]);
		