
import __ASTRO_IMAGE_IMPORT_0 from "./cover.jpg?astroContentImageFlag=&importer=content%2Fblog%2F2026%2Fdesigning-personal-publication%2Fde.mdx";
import __ASTRO_IMAGE_IMPORT_1 from "./cover.jpg?astroContentImageFlag=&importer=content%2Fblog%2F2026%2Fdesigning-personal-publication%2Fen.mdx";
import __ASTRO_IMAGE_IMPORT_2 from "./cover.jpg?astroContentImageFlag=&importer=content%2Fblog%2F2026%2Fdesigning-personal-publication%2Ffr.mdx";
import __ASTRO_IMAGE_IMPORT_3 from "./cover.jpg?astroContentImageFlag=&importer=content%2Fblog%2F2026%2Fdesigning-personal-publication%2Fja.mdx";
import __ASTRO_IMAGE_IMPORT_4 from "./cover.jpg?astroContentImageFlag=&importer=content%2Fblog%2F2026%2Fdesigning-personal-publication%2Fzh-CN.mdx";
import __ASTRO_IMAGE_IMPORT_5 from "./cover.jpg?astroContentImageFlag=&importer=content%2Fblog%2F2026%2Ffuture-of-static-web%2Fen.mdx";
import __ASTRO_IMAGE_IMPORT_6 from "./cover.jpg?astroContentImageFlag=&importer=content%2Fblog%2F2026%2Ffuture-of-static-web%2Fja.mdx";
import __ASTRO_IMAGE_IMPORT_7 from "./cover.jpg?astroContentImageFlag=&importer=content%2Fblog%2F2026%2Ffuture-of-static-web%2Fzh-CN.mdx";
import __ASTRO_IMAGE_IMPORT_8 from "./cover.jpg?astroContentImageFlag=&importer=content%2Fblog%2F2026%2Fminimal-markdown-craft%2Fen.md";
import __ASTRO_IMAGE_IMPORT_9 from "./cover.jpg?astroContentImageFlag=&importer=content%2Fblog%2F2026%2Fminimal-markdown-craft%2Fzh-CN.md";
import __ASTRO_IMAGE_IMPORT_10 from "./cover.jpg?astroContentImageFlag=&importer=content%2Fblog%2F2026%2Funreleased-draft%2Fen.mdx";
export default new Map([["./cover.jpg?astroContentImageFlag=&importer=content%2Fblog%2F2026%2Fdesigning-personal-publication%2Fde.mdx", __ASTRO_IMAGE_IMPORT_0], ["./cover.jpg?astroContentImageFlag=&importer=content%2Fblog%2F2026%2Fdesigning-personal-publication%2Fen.mdx", __ASTRO_IMAGE_IMPORT_1], ["./cover.jpg?astroContentImageFlag=&importer=content%2Fblog%2F2026%2Fdesigning-personal-publication%2Ffr.mdx", __ASTRO_IMAGE_IMPORT_2], ["./cover.jpg?astroContentImageFlag=&importer=content%2Fblog%2F2026%2Fdesigning-personal-publication%2Fja.mdx", __ASTRO_IMAGE_IMPORT_3], ["./cover.jpg?astroContentImageFlag=&importer=content%2Fblog%2F2026%2Fdesigning-personal-publication%2Fzh-CN.mdx", __ASTRO_IMAGE_IMPORT_4], ["./cover.jpg?astroContentImageFlag=&importer=content%2Fblog%2F2026%2Ffuture-of-static-web%2Fen.mdx", __ASTRO_IMAGE_IMPORT_5], ["./cover.jpg?astroContentImageFlag=&importer=content%2Fblog%2F2026%2Ffuture-of-static-web%2Fja.mdx", __ASTRO_IMAGE_IMPORT_6], ["./cover.jpg?astroContentImageFlag=&importer=content%2Fblog%2F2026%2Ffuture-of-static-web%2Fzh-CN.mdx", __ASTRO_IMAGE_IMPORT_7], ["./cover.jpg?astroContentImageFlag=&importer=content%2Fblog%2F2026%2Fminimal-markdown-craft%2Fen.md", __ASTRO_IMAGE_IMPORT_8], ["./cover.jpg?astroContentImageFlag=&importer=content%2Fblog%2F2026%2Fminimal-markdown-craft%2Fzh-CN.md", __ASTRO_IMAGE_IMPORT_9], ["./cover.jpg?astroContentImageFlag=&importer=content%2Fblog%2F2026%2Funreleased-draft%2Fen.mdx", __ASTRO_IMAGE_IMPORT_10]]);
		